### ISSUE TITLE
SverchokRedux upgrade on the fly ?

### ISSUE THREAD

**Issue by zeffii** [Sverchok/SverchokRedux#23]
This is a soft issue, maybe a non issue, but I'd like to approach it anyway.

 _upgrade on demand_ was great for non-git users to get the latest zip auto-installed, but it almost automatically makes it difficult for them to test branches, perhaps we can provide a way to get a branch too. 

Ideally we would be able to convince more people to use GIT so they can test branches before we commit to master, it's very frustrating to realize that many features aren't tested by more than the core team until it hits master. People think they're helping but really they make more work for us by not having access to branches conveniently.

**Comment by ly29** [comment]
Yeah, we could look into git http/html api and make trying out different features possible.
One important thing however is to have a main distribution with a nice root folder name to avoid hackery like the old system.
Also, since nodes are totally dynamic we should look into keeping distributable in a simple way.
A lot if that infrastructure could probably be reused for a convenient script prototype system like script nodes.

**Comment by ly29** [comment]
I think while not urgent it is good to solve this quickly to be able to get feedback once we get it off the ground. Which I think is soon, I just need some time to sort out the implications of the new type system...
The node writing and other wrinkles are better sorted out with some feedback while still maintaining coherence of the overall system.

**Comment by ly29** [comment]
It would be nice if we had a deployment system in place. Even if we don't code it yet knowing what we want it to do makes it easier to accomplish.
- a well namned easy installable zip package
- updating in place from add on
- switching between branches
- automatic testing before making new master version available, of course won't catch all bugs but some basic test that it loads, nodes can be serialized and loaded, some test layouts can be run and results verified.
